# Generated by Django 4.2.4 on 2023-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("mileage", models.PositiveIntegerField()),
            ],
        ),
    ]
