# Generated by Django 4.2.4 on 2023-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motors',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
